# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { 
      #device = "/dev/disk/by-uuid/47007a19-7927-4553-8c3a-dea4ab12980a";
      device = "/dev/mapper/luks-30bdd157-9f8f-422f-9131-1dd1735830a0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-30bdd157-9f8f-422f-9131-1dd1735830a0".device = "/dev/disk/by-uuid/30bdd157-9f8f-422f-9131-1dd1735830a0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C6D4-7611";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f8ee24d6-cece-4e30-b2b2-ac18072770ed"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.virtualbox.guest.enable = true;
}

